# usage: ansible-playbook example-playbook.yml
---
- name: install git
  hosts: vagrant
  sudo: True
  user: vagrant
  gather_facts: False
  vars:
    git_username: username
    git_usermail: mail@example.com
  tasks:
    - include: roles/nginx/tasks/main.yml
  handlers:
    - include: roles/nginx/handlers/main.yml